language: java
sudo: required
git:
  depth: false
addons:
  sonarcloud:
    organization: "vatbub-github"
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
install:
  - wget https://s3.eu-central-1.amazonaws.com/vatbubjdk/OpenJDK21U-jdk_x64_linux_hotspot_21.0.8_9.tar.gz -nv
  - tar -xf OpenJDK21U-jdk_x64_linux_hotspot_21.0.8_9.tar.gz
  - export JAVA_HOME=/home/travis/build/vatbub/kotlinPreferences/jdk-21.0.8+9
script:
  - mvn verify -DtrimStackTrace=false --settings travisMavenSettings.xml
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then mvn deploy --settings travisMavenSettings.xml; fi
notifications:
  email:
    recipients:
      - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
